### ISSUE TITLE
windows NVIDA use stable diffusion but header etag is missing 

### ISSUE THREAD

**Issue by doraemoncandy** [evilsocket/cake#37]
![image](https://github.com/user-attachments/assets/c0dcc0df-8453-415e-8af9-07e1ed0dd10b)

I want to make my nb (windows11, NV 4090) be a work node, so I use the following command

`cake-cli --model ./cake-data/SD-XL --mode worker --name nb4090  --model-type image-model --topology topology-sd.yml
`
but I get the error 'Error: Header etag is missing' 

this is my `topology-sd.yml `
```

mac:
  host: '100.119.102.31:10128'
  description: 'Mac Host'
  layers:
    - clip
    - vae
nb4090:
  host: '100.114.71.72:10128'
  description: '4090'
  layers:
    - unet

```

and all my sd model file show on the image
seems I have already downloaded the model I need, but I still get error... I am not sure where is the problem.. how can I do next..
thanks
